// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
  url: "postgresql://postgres.esncvtpqdnsjpczbhyrt:OZRZy006vqX4uo@aws-1-us-east-1.pooler.supabase.com:5432/postgres",
  },
});
